### ISSUE TITLE
Yoast metabox low

### ISSUE THREAD

**Issue by samikeijonen** [MEOM/meom-dodo#7]
Should we move Yoast metabox lower in this plugin or in Kala?

cc: @giraffewoods

**Comment by giraffewoods** [comment]
I think that it should be in Kala. It is steady filter and I would like to offer possibility to undo everything this plugin does. In this case it would seem a bit strange to write a filter which manipulates filter :)

**Comment by samikeijonen** [comment]
Roger that, closing out.
